name: 'Setup env, lint, test and build elm-minesweeper'
description: 'Internal reusable action to run tests, lint and build elm-minesweeper'
runs:
  using: composite
  steps:
  # Setup node
  - name: Setup node
    uses: actions/setup-node@v4
    with:
      node-version-file: '.nvmrc'
      cache: 'npm'

  - name: using cache for .elm
    uses: actions/cache@v3
    with:
      path: '~/.elm'
      key: ${{ runner.os }}-elm-${{ hashFiles('./elm-tooling.json') }}

  - name: Install node dependencies
    shell: bash
    run: |
      NO_ELM_TOOLING_INSTALL=true 
      npm ci --prefer-offline
      npx --no-install elm-tooling install

  - name: Making sure the installation worked
    shell: bash
    run: |
      npx elm --version
      node --version
      npm --version

  - name: Lint source
    shell: bash
    run: npx elm-format ./src ./tests --validate

  - name: Run tests
    shell: bash
    run: npm run test
    
  - name: Build elm application
    shell: bash
    run: npm run build