# This is a basic workflow to help you get started with Actions

name: Build and deploy elm-minesweeper

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-and-build:
    needs: define-artifact-name
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-lint-test-build

      - uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: ./build/

  publish-build:
    needs: 
      - call-test-and-build-workflow
      - define-artifact-name
    runs-on: ubuntu-latest
    steps:
      - name: download artefacts
        uses: actions/download-artifact@v2
        with:
          artefact-name: production-build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build