# This is a basic workflow to help you get started with Actions

name: Build and deploy elm-minesweeper

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  define-artifact-name:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.echo-artifact-name.outputs.artifact-name }}
    steps:
      - id: echo-artifact-name
        name: echo-artifact-name
        run: echo "::set-output name=artifact-name::production-build"
  
  call-test-and-build-workflow:
    needs: define-artifact-name
    runs-on: ubuntu-latest
    steps:
  
      - uses: ${{ github.repository }}/.github/workflows/test-and-build-workflow.yaml@${{ github.sha }}
        with:
          artefact-name: ${{ needs.define-artifact-name.outputs.artifact-name }}

  publish-build:
    needs: 
      - call-test-and-build-workflow
      - define-artifact-name
    runs-on: ubuntu-latest
    steps:
      - name: download artefacts
        uses: actions/download-artifact@v2
        with:
          artefact-name: ${{ needs.define-artifact-name.outputs.artifact-name }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build